### ISSUE TITLE
Override packaging check for deploy-war

### ISSUE THREAD

**Issue by jkutner** [heroku/heroku-maven-plugin#15]
Currently, the `heroku:deploy-war` goal fails if the `pom.xml` is not configured with `war` packaging. We should add a flag to the plugin config that disables this.

**Comment by yarrumretep** [comment]
Please add this modification.  It will allow developers to deploy otherwise-built war files (e.g. grails, ant, etc) in configurations that could include additional artifacts (e.g. New Relic jar, choice of runner, custom Proc file, etc).  Command-line war deployment with the toolbelt doesn't currently allow for anything but a simple war deploy.
